steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'frontend/Dockerfile'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/mentor-ai/frontend:latest'
      - '.'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/mentor-ai/frontend:latest'
